MedOR/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MedOR.Common;

namespace MedOR.Controllers
{
    [Authorize]
    public class SecurityController : Controller
    {
        //
        // GET: /Security/

        #region Constructor
        private DataServices.Service _MedOrSvc;

        public SecurityController()
        {
            _MedOrSvc = new DataServices.Service();
        }
        #endregion

        public ActionResult Index()
        {
            return View();
        }

        [Comm.AuthorizeUser(AccessLevel = "View Roles")]
        public ActionResult ListOfRoles()
        {
            var userId = HttpContext.User.Identity.Name;
            var roles = _MedOrSvc.GetRoleAndPermissions(new Guid(userId));
            return View(roles);
        }

        [HttpPost]
        public ActionResult ListOfRoles(int i)
        {
            return View();
        }

        [Comm.AuthorizeUser(AccessLevel = "Create Roles")]
        public ActionResult CreateNewRole()
        {
            var model = _MedOrSvc.GetAllPermissionsAndUsersForRoleModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateNewRole(DataModel.RoleModel model) 
        {
            if (ModelState.IsValid)
            {
                model.CreatedOn = DateTime.Now;
                model.CreatedBy = new Guid(HttpContext.User.Identity.Name);
                var newSecurity = _MedOrSvc.AddNewSecurityRole(model);

                if (newSecurity != 0)
                    return Redirect("/Security/ListOfRoles");
            }
            model = _MedOrSvc.GetAllPermissionsAndUsersForRoleModel();
            return View(model);
        }

        [Comm.AuthorizeUser(AccessLevel = "Edit Roles")]
        public ActionResult EditRole(Guid id)
        {
            var model = _MedOrSvc.GetRoleByID(id);
            model.PermissionModels = _MedOrSvc.GetAllPermissionsForRoleModel(id);
            if (model == null)
            {
               // return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult EditRole(DataModel.RoleModel model)
        {
            if (ModelState.IsValid)
            {
                model.ModifiedBy = new Guid(HttpContext.User.Identity.Name);
                model.ModifiedOn = DateTime.Now;
                var updateRole = _MedOrSvc.UpdateSecurityRole(model);

                if (updateRole != 0)
                    return Redirect("/Security/ListOfRoles");
            }
            return View(model);
        }

        [Comm.AuthorizeUser(AccessLevel = "Delete Roles")]
        public ActionResult DeleteRole(Guid id)
        {
            var deleted = _MedOrSvc.DeleteRoleByID(id);
            if (deleted != 0)
                return Redirect("/Security/ListOfRoles");
            return View();
        }
    }
}

MedOR/Views/Security/CreateNewRole.cshtml
@{
    ViewBag.Title = "CreateNewRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model DataModel.RoleModel
<!-- start: PAGE HEADER -->
@section CSS{
    <link rel="stylesheet" href="~/Content/assets/plugins/summernote/build/summernote.css" />
    <link rel="stylesheet" href="~/Content/assets/plugins/select2/select2.css" />
}
<div class="row">
    <div class="col-sm-12">
        <!-- start: PAGE TITLE & BREADCRUMB -->
        <ol class="breadcrumb">
            <li><i class="clip-file"></i><a href="ListOfRoles"> Roles & Permissions </a></li>
            <li class="active">Create New... </li>
        </ol>
        <div class="page-header">
            <h1>
                New Role & Permissions <small>create new role & permissions</small></h1>
        </div>
        <!-- end: PAGE TITLE & BREADCRUMB -->
    </div>
</div>
<!-- end: PAGE HEADER -->
<div class="row">
    <div class="col-md-12">
        <!-- start: FORM VALIDATION 1 PANEL -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-external-link-square"></i>New Role & Permissions
                <div class="panel-tools">
                    @*<a class="btn btn-xs btn-link panel-collapse collapses" href="#"></a><a class="btn btn-xs btn-link panel-config"
                        href="#panel-config" data-toggle="modal"><i class="fa fa-wrench"></i></a><a class="btn btn-xs btn-link panel-refresh"
                            href="#"><i class="fa fa-refresh"></i></a><a class="btn btn-xs btn-link panel-expand"
                                href="#"><i class="fa fa-resize-full"></i></a><a class="btn btn-xs btn-link panel-close"
                                    href="#"><i class="fa fa-times"></i></a>*@
                </div>
            </div>
            <div class="panel-body">
                <h2>
                    <i class="fa fa-pencil-square teal"></i>Create new role & permissions</h2>
                <p>
                    Create new role & permissions.
                </p>
                <hr />
                <form method="post" id="form" action="">
                <div class="row">
                    <div class="col-md-12">
                        <div class="errorHandler alert alert-danger no-display">
                            <i class="fa fa-times-sign"></i>You have some form errors. Please check below.
                        </div>
                        <div class="successHandler alert alert-success no-display">
                            <i class="fa fa-ok"></i>Your form validation is successful!
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">
                                Name <span class="symbol required"></span>
                            </label>
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", id = "name", Name = "name", placeholder = "Insert role's name" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-8">
                        <div class="alert alert-info">
                            Assign Permissions & Users to this role.
                        </div>
                        <div class="tabbable tabs-left">
                            <ul id="myTab3" class="nav nav-tabs tab-green">
                                <li class="active"><a href="#panel_tab4_example1" data-toggle="tab"><i class="pink fa fa-key">
                                </i> Permissions </a></li>
                                <li class=""><a href="#panel_tab4_example2" data-toggle="tab"><i class="blue fa fa-users">
                                </i> Users </a></li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="panel_tab4_example1">
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-hover" id="sample-table-1">
                                            <thead>
                                                <tr>
                                                    <th>
                                                        Permission Name
                                                    </th>
                                                    <th class="center">
                                                        View @*<div class="checkbox-table">
                                                            <label>
                                                                View <input type="checkbox" class="flat-grey"/>
                                                            </label>
                                                        </div>*@
                                                    </th>
                                                    <th class="center">
                                                        Create @*<div class="checkbox-table">
                                                            <label>
                                                                Create <input type="checkbox" class="flat-grey"/>
                                                            </label>
                                                        </div>*@
                                                    </th>
                                                    <th class="center">
                                                        Edit @* <div class="checkbox-table">
                                                            <label>
                                                               Edit <input type="checkbox" class="flat-grey"/>
                                                            </label>
                                                        </div>*@
                                                    </th>
                                                    <th class="center">
                                                        Delete @*<div class="checkbox-table">
                                                            <label>
                                                                <input type="checkbox" class="flat-grey"/>
                                                            </label>
                                                        </div>*@
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @for (int i = 0; i < @Model.PermissionModels.Count(); i++)
                                                {
                                                    @Html.HiddenFor(x => x.PermissionModels[i].PermissionID)
                                                    <tr>
                                                        <td>
                                                            @Html.DisplayTextFor(x => x.PermissionModels[i].PermissionName)
                                                        </td>
                                                        <td class="center">
                                                            <div class="checkbox-table">
                                                                <label>
                                                                    @Html.CheckBoxFor(x => x.PermissionModels[i].View, new { @class = "flat-grey" })
                                                                </label>
                                                            </div>
                                                        </td>
                                                        <td class="center">
                                                            <div class="checkbox-table">
                                                                <label>
                                                                    @Html.CheckBoxFor(x => x.PermissionModels[i].Create, new { @class = "flat-grey" })
                                                                </label>
                                                            </div>
                                                        </td>
                                                        <td class="center">
                                                            <div class="checkbox-table">
                                                                <label>
                                                                    @Html.CheckBoxFor(x => x.PermissionModels[i].Edit, new { @class = "flat-grey" })
                                                                </label>
                                                            </div>
                                                        </td>
                                                        <td class="center">
                                                            <div class="checkbox-table">
                                                                <label>
                                                                    @Html.CheckBoxFor(x => x.PermissionModels[i].Delete, new { @class = "flat-grey" })
                                                                </label>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane" id="panel_tab4_example2">
                                    <div class="form-group">
                                        <div>
                                            @Html.ListBoxFor(m => m.SelectedUserIDs, MedOR.Common.Comm.GetUserList(@Model.UserModels), new { multiple = "multiple", @class = "form-control search-select", id = "form-field-select-4", placeholder = "Click here to select users" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <span class="symbol required"></span>Required Fields
                            <hr />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <button class="btn btn-light-grey btn-block" type="button" onclick="window.location='/Security/ListOfRoles';">
                            Cancel
                        </button>
                    </div>
                    <div class="col-md-4">
                        <p>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <button class="btn btn-blue btn-block" type="submit">
                            Save
                        </button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <!-- end: FORM VALIDATION 1 PANEL -->
    </div>
</div>
<!-- end: PAGE CONTENT-->
@section Scripts{
    <script type="text/javascript" src="~/Content/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/summernote/build/summernote.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/ckeditor/adapters/jquery.js"></script>
    <script type="text/javascript" src="~/Content/assets/js/form-validation.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/autosize/jquery.autosize.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/jquery.maskedinput/src/jquery.maskedinput.js"></script>
    <script type="text/javascript" src="~/Content/assets/js/form-elements.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            FormValidator.init();
            FormElements.init();
        });
    </script>
}

MedOR/Views/Security/ListOfRoles.cshtml
@{
    ViewBag.Title = "List Of Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<DataModel.RoleModel>
@section CSS{
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/select2/select2.css" />
    <link rel="stylesheet" href="~/Content/assets/plugins/DataTables/media/css/DT_bootstrap.css" />
}
<!-- start: PAGE CONTENT -->
<!-- start: PAGE HEADER -->
<!-- start: PANEL CONFIGURATION MODAL FORM -->
<div class="modal fade" id="panel-remove" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    Remove Role</h4>
            </div>
            <div id="modalbody" class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Cancel</button>
                <button type="button" onclick="return execRemove()" class="btn btn-primary">
                    OK</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@Html.Action("_CreateModify", "Home", new { TableName = "Roles" })
<!-- /.modal -->
<!-- end: SPANEL CONFIGURATION MODAL FORM -->
<div class="row">
    <div class="col-sm-12">
        <!-- start: PAGE TITLE & BREADCRUMB -->
        <ol class="breadcrumb">
            <li><i class="clip-file"></i><a href="#"> Roles </a></li>
            <li class="active">List Of Roles </li>
        </ol>
        <div class="page-header">
            <h1>
                List Of Roles <small>list of roles</small></h1>
        </div>
        <!-- end: PAGE TITLE & BREADCRUMB -->
    </div>
</div>
<!-- end: PAGE HEADER -->
<!-- start: PAGE CONTENT -->
<div class="row">
    <div class="col-md-12">
        <!-- start: DYNAMIC TABLE PANEL -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-external-link-square"></i>Roles
                <div class="panel-tools">
                    <a class="btn btn-xs btn-link panel-collapse collapses" href="#"></a><a class="btn btn-xs btn-link panel-config"
                        href="#panel-config" data-toggle="modal"><i class="fa fa-wrench"></i></a><a class="btn btn-xs btn-link panel-refresh"
                            href="@Url.Action("ListOfRoles", "Security")"><i class="fa fa-refresh"></i></a><a class="btn btn-xs btn-link panel-expand"
                                href="#"><i class="fa fa-resize-full"></i></a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                    <thead>
                        <tr>
                            <th class="center">
                                #
                            </th>
                            <th class="hidden-xs">
                                Name
                            </th>
                            <th>
                                Created On
                            </th>
                            <th>
                                Created By
                            </th>
                            <th>
                                Modified On
                            </th>
                            <th>
                                Modified By
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                            foreach (var role in @Model.ToList().OrderBy(l => l.Name))
                            {
                                if (role.SecurityModel.View)
                                { 
                                    <tr id="@role.RoleID" name="@role.Name">
                                        <td class="center">
                                            @i
                                        </td>
                                        <td class="hidden-xs">
                                            @role.Name
                                        </td>
                                        <td>
                                            @role.CreatedOn
                                        </td>
                                        <td>
                                            @role.CreatedByName
                                        </td>
                                        <td>
                                            @role.ModifiedOn
                                        </td>
                                        <td>
                                            @role.ModifiedByName
                                        </td>
                                        <td class="center">
                                            <div class="visible-md visible-lg hidden-sm hidden-xs">
                                                @if (role.SecurityModel.Edit)
                                                {
                                                    <a href="/Security/EditRole?id=@role.RoleID" class="btn btn-xs btn-teal tooltips"
                                        data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
                                                }
                                                @if (role.SecurityModel.Delete)
                                                {
                                                    <a href="#panel-remove" class="btn btn-xs btn-bricky tooltips" data-placement="top"
                                                        data-original-title="Remove" data-toggle="modal"><i class="fa fa-times fa fa-white">
                                                        </i></a>
                                                }
                                            </div>
                                            <div class="visible-xs visible-sm hidden-md hidden-lg">
                                                <div class="btn-group">
                                                    <a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"><i
                                                        class="fa fa-cog"></i><span class="caret"></span></a>
                                                    <ul role="menu" class="dropdown-menu
                                        pull-right">
                                                        @if (role.SecurityModel.Edit)
                                                        {
                                                            <li role="presentation"><a role="menuitem" tabindex="-1" href="/Security/EditRole?id=@role.RoleID">
                                                                <i class="fa fa-edit"></i>Edit </a></li>
                                                        }
                                                        @if (role.SecurityModel.Delete)
                                                        {
                                                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#panel-remove"><i
                                                                class="fa fa-times"></i>Remove </a></li>
                                                        }
                                                    </ul>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                                i++;
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end: DYNAMIC TABLE PANEL -->
    </div>
</div>
<!-- end: PAGE CONTENT-->
@section Scripts{
    <script type="text/javascript" src="~/Content/assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/DataTables/media/js/DT_bootstrap.js"></script>
    <script type="text/javascript" src="~/Content/assets/js/table-data.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            TableData.init();

            if ($('#viewCreatedBy').val() == 'True') {
                $('td:nth-child(3),th:nth-child(3)').show();
            }
            else if ($('#viewCreatedBy').val() == 'False') {
                $('td:nth-child(3),th:nth-child(3)').hide();
            }
            else { }

            if ($('#viewCreatedOn').val() == 'True') {
                $('td:nth-child(4),th:nth-child(4)').show();
            }
            else if ($('#viewCreatedOn').val() == 'False') {
                $('td:nth-child(4),th:nth-child(4)').hide();
            }
            else { }

            if ($('#viewModifiedBy').val() == 'True') {
                $('td:nth-child(5),th:nth-child(5)').show();
            }
            else if ($('#viewModifiedBy').val() == 'False') {
                $('td:nth-child(5),th:nth-child(5)').hide();
            }
            else { }

            if ($('#viewModifiedOn').val() == 'True') {
                $('td:nth-child(6),th:nth-child(6)').show();
            }
            else if ($('#viewModifiedOn').val() == 'False') {
                $('td:nth-child(6),th:nth-child(6)').hide();
            }
            else { }
        });

        function updateView() {
            if ($('#viewCreatedBy').is(":checked")) {
                $('td:nth-child(3),th:nth-child(3)').show();
            }
            else {
                $('td:nth-child(3),th:nth-child(3)').hide();
            }

            if ($('#viewCreatedOn').is(":checked")) {
                $('td:nth-child(4),th:nth-child(4)').show();
            }
            else {
                $('td:nth-child(4),th:nth-child(4)').hide();
            }

            if ($('#viewModifiedBy').is(":checked")) {
                $('td:nth-child(5),th:nth-child(5)').show();
            }
            else {
                $('td:nth-child(5),th:nth-child(5)').hide();
            }

            if ($('#viewModifiedOn').is(":checked")) {
                $('td:nth-child(6),th:nth-child(6)').show();
            }
            else {
                $('td:nth-child(6),th:nth-child(6)').hide();
            }
        }


        //Modal OK
        var id = '';
        $('tr').click(function () {
            id = $(this).attr('id');
            var name = $(this).attr('name');
            document.getElementById('modalbody').innerHTML = 'Are you sure you want to remove ' + name + '?';
        });

        function execRemove() {
            window.location.href = "/Security/DeleteRole?id=" + id;
            return false;
        }
    </script>
}