MedOR/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MedOR.Common;

namespace MedOR.Controllers
{
    [Authorize]
    public class DoctorController : Controller
    {
        //
        // GET: /Doctor/

        #region Constructor
        private DataServices.Service _MedOrSvc;

        public DoctorController()
        {
            _MedOrSvc = new DataServices.Service();
        }
        #endregion

        public ActionResult Index()
        {
            return View();
        }

        [Comm.AuthorizeUser(AccessLevel = "View Doctors")]
        public ActionResult ListOfDoctors()
        {
            var doctors = _MedOrSvc.GetDoctorsByUserID(new Guid(HttpContext.User.Identity.Name));
            return View(doctors);
        }

        [Comm.AuthorizeUser(AccessLevel = "Create Doctors")]
        public ActionResult CreateNewDoctor()
        {
            var model = _MedOrSvc.GetSpecialties();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateNewDoctor(DataModel.DoctorModel model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedOn = DateTime.Now;
                model.CreatedBy = new Guid(HttpContext.User.Identity.Name);
                var newDoctor = _MedOrSvc.AddNewDoctor(model);

                if (newDoctor != 0)
                    return Redirect("/Doctor/ListOfDoctors");
            }
            model = _MedOrSvc.GetSpecialties();
            return View(model);
        }

        [Comm.AuthorizeUser(AccessLevel = "Edit Doctors")]
        public ActionResult EditDoctor(Guid id)
        {
            var model = _MedOrSvc.GetDoctorByID(id);
            if (model == null)
            {
                // return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult EditDoctor(DataModel.DoctorModel model)
        {
            if (ModelState.IsValid)
            {
                model.ModifiedBy = new Guid(HttpContext.User.Identity.Name);
                model.ModifiedOn = DateTime.Now;
                var editDoctor = _MedOrSvc.UpdateDoctor(model);

                if (editDoctor != 0)
                    return Redirect("/Doctor/ListOfDoctors");
            }
            return View();
        }

        [Comm.AuthorizeUser(AccessLevel = "Delete Doctors")]
        public ActionResult DeleteDoctor(Guid id)
        {
            var deleted = _MedOrSvc.DeleteDoctorByID(id);
            if (deleted != 0)
                return Redirect("/Doctor/ListOfDoctors");
            return View();
        }
    }
}

MedOR/Views/Doctor/CreateNewDoctor.cshtml
@{
    ViewBag.Title = "CreateNewDoctor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model DataModel.DoctorModel
<!-- start: PAGE HEADER -->
@section CSS{
    <link rel="stylesheet" href="~/Content/assets/plugins/summernote/build/summernote.css" />
    <link rel="stylesheet" href="~/Content/assets/plugins/select2/select2.css" />
}
<div class="row">
    <div class="col-sm-12">
        <!-- start: PAGE TITLE & BREADCRUMB -->
        <ol class="breadcrumb">
            <li><i class="clip-file"></i><a href="#"> Doctors </a></li>
            <li class="active">Create New... </li>
        </ol>
        <div class="page-header">
            <h1>
                New Doctor <small>create new doctor</small></h1>
        </div>
        <!-- end: PAGE TITLE & BREADCRUMB -->
    </div>
</div>
<!-- end: PAGE HEADER -->
<div class="row">
    <div class="col-md-12">
        <!-- start: FORM VALIDATION 1 PANEL -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-external-link-square"></i>New Doctor
                <div class="panel-tools">
                   @* <a class="btn btn-xs btn-link panel-collapse collapses" href="#"></a><a class="btn btn-xs btn-link panel-config"
                        href="#panel-config" data-toggle="modal"><i class="fa fa-wrench"></i></a><a class="btn btn-xs btn-link panel-refresh"
                            href="#"><i class="fa fa-refresh"></i></a><a class="btn btn-xs btn-link panel-expand"
                                href="#"><i class="fa fa-resize-full"></i></a><a class="btn btn-xs btn-link panel-close"
                                    href="#"><i class="fa fa-times"></i></a>*@
                </div>
            </div>
            <div class="panel-body">
                <h2>
                    <i class="fa fa-pencil-square teal"></i>Create a new doctor</h2>
                <p>
                    Create a new Doctor.
                </p>
                <hr />
                <form method="post" id="form" action="">
                <div class="row">
                    <div class="col-md-12">
                        <div class="errorHandler alert alert-danger no-display">
                            <i class="fa fa-times-sign"></i>You have some form errors. Please check below.
                        </div>
                        <div class="successHandler alert alert-success no-display">
                            <i class="fa fa-ok"></i>Your form validation is successful!
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label">
                                First Name <span class="symbol required"></span>
                            </label>
                            @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control", id = "firstname", Name = "firstname", placeholder = "Insert doctor's first name" })
                        </div>
                         <div class="form-group">
                            <label class="control-label">
                                Last Name <span class="symbol required"></span>
                            </label>
                            @Html.TextBoxFor(x => x.LastName, new { @class = "form-control", id = "lastname", Name = "lastname", placeholder = "Insert doctor's last name" })
                        </div>
                        @*<div class="form-group">
                            <label class="control-label">
                                Phone <span class="symbol required"></span>
                            </label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                                <input type="text" id="phone" placeholder="Insert clinic's phone" class="form-control input-mask-phone"
                                    name="phone" />
                            </div>
                        </div>*@
                        <div class="form-group">
                            <label class="control-label">
                                Mobile Phone <span class="symbol required"></span>
                            </label>
                            <span class="input-icon">
                            @Html.TextBoxFor(x => x.MobilePhone, new { @class = "form-control", id = "mobilephone", Name = "mobilephone" })
                            <i class="fa fa-phone"></i></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">
                                Work Phone 
                            </label>
                            <span class="input-icon">
                            @Html.TextBoxFor(x => x.WorkPhone, new { @class = "form-control", id = "workphone", Name = "workphone" }) 
                            <i class="fa fa-phone"></i></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">
                                Email 
                            </label>
                            <span class="input-icon">
                            @Html.TextBoxFor(x => x.Email, new { @class = "form-control", id = "email", Name = "email" }) 
                            <i class="fa fa-envelope"></i></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">
                                Specialty <span class="symbol required"></span>
                            </label>
                            @Html.DropDownListFor(m => m.Specialty, MedOR.Common.Comm.GetSpecialtyList(@Model.DropDownModel), "--Select doctor's specialty--", new { @class = "form-control", id = "specialty", Name = "specialty" })
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <span class="symbol required"></span>Required Fields
                            <hr />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <button class="btn btn-light-grey btn-block" type="button" onclick="window.location='/Doctor/ListOfDoctors';">
                            Cancel
                        </button>
                    </div>
                    <div class="col-md-4">
                        <p>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <button class="btn btn-blue btn-block" type="submit">
                            Save
                        </button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <!-- end: FORM VALIDATION 1 PANEL -->
    </div>
</div>
<!-- end: PAGE CONTENT-->
@section Scripts{
    <script type="text/javascript" src="~/Content/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/summernote/build/summernote.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/ckeditor/adapters/jquery.js"></script>
    <script type="text/javascript" src="~/Content/assets/js/form-validation.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/autosize/jquery.autosize.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/jquery.maskedinput/src/jquery.maskedinput.js"></script>
    <script type="text/javascript" src="~/Content/assets/js/form-elements.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            FormElements.init();
            FormValidator.init();
        });
    </script>
}

MedOR/Views/Doctor/ListOfDoctors.cshtml
@{
    ViewBag.Title = "List Of Doctors";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<DataModel.DoctorModel>
@section CSS{
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/select2/select2.css" />
    <link rel="stylesheet" href="~/Content/assets/plugins/DataTables/media/css/DT_bootstrap.css" />
}
<!-- start: PAGE CONTENT -->
<!-- start: PAGE HEADER -->
<!-- start: PANEL CONFIGURATION MODAL FORM -->
<div class="modal fade" id="panel-remove" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    Remove Doctor</h4>
            </div>
            <div id="modalbody" class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Cancel</button>
                <button type="button" onclick="return execRemove()" class="btn btn-primary">
                    OK</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@Html.Action("_CreateModify", "Home", new { TableName = "Doctors" })
<!-- /.modal -->
<!-- end: SPANEL CONFIGURATION MODAL FORM -->
<div class="row">
    <div class="col-sm-12">
        <!-- start: PAGE TITLE & BREADCRUMB -->
        <ol class="breadcrumb">
            <li><i class="clip-file"></i><a href="#"> Doctors </a></li>
            <li class="active">List Of Doctors </li>
        </ol>
        <div class="page-header">
            <h1>
                List Of Doctors <small>list of doctors</small></h1>
        </div>
        <!-- end: PAGE TITLE & BREADCRUMB -->
    </div>
</div>
<!-- end: PAGE HEADER -->
<!-- start: PAGE CONTENT -->
<div class="row">
    <div class="col-md-12">
        <!-- start: DYNAMIC TABLE PANEL -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-external-link-square"></i>Doctors
                <div class="panel-tools">
                    <a class="btn btn-xs btn-link panel-collapse collapses" href="#"></a><a class="btn btn-xs btn-link panel-config"
                        href="#panel-config" data-toggle="modal"><i class="fa fa-wrench"></i></a><a class="btn btn-xs btn-link panel-refresh"
                            href="@Url.Action("ListOfDoctors", "Doctor")"><i class="fa fa-refresh"></i></a><a class="btn btn-xs btn-link panel-expand"
                                href="#"><i class="fa fa-resize-full"></i></a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
                    <thead>
                        <tr>
                            <th class="center">
                                #
                            </th>
                            <th class="hidden-xs">
                                First Name
                            </th>
                            <th>
                                Last Name
                            </th>
                            <th class="hidden-xs">
                                Specialty
                            </th>
                            <th>
                                Phone
                            </th>
                            <th>
                                Created By
                            </th>
                            <th>
                                Created On
                            </th>
                            <th>
                                Modified By
                            </th>
                            <th>
                                Modified On
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                            foreach (var doctor in @Model.ToList())
                            {
                                if (doctor.SecurityModel.View)
                                {   
                            <tr id="@doctor.DoctorID" name="@doctor.FirstName @doctor.LastName">
                                <td class="center">
                                    @i
                                </td>
                                <td class="hidden-xs">
                                    @doctor.FirstName
                                </td>
                                <td>
                                    @doctor.LastName
                                </td>
                                <td class="hidden-xs">
                                    @doctor.SpecialtyName
                                </td>
                                <td>
                                    @if(!String.IsNullOrEmpty(doctor.MobilePhone)) 
                                    { 
                                        @doctor.MobilePhone
                                    } 
                                    else  
                                    {
                                        @doctor.WorkPhone
                                    }
                                </td>
                                <td>
                                    @doctor.CreatedByName
                                </td>
                                <td>
                                    @doctor.CreatedOn
                                </td>
                                <td>
                                    @doctor.ModifiedByName
                                </td>
                                <td>
                                    @doctor.ModifiedOn
                                </td>
                                <td class="center">
                                    <div class="visible-md visible-lg hidden-sm hidden-xs">
                                        @if (doctor.SecurityModel.Edit)
                                        {
                                            <a href="/Doctor/EditDoctor?id=@doctor.DoctorID" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit">
                                                <i class="fa fa-edit"></i></a>
                                        }
                                        @if (doctor.SecurityModel.Delete)
                                        {
                                            <a href="#panel-remove" class="btn btn-xs btn-bricky tooltips" data-placement="top"
                                                data-original-title="Remove" data-toggle="modal"><i class="fa fa-times fa fa-white">
                                                </i></a>
                                        }
                                    </div>
                                    <div class="visible-xs visible-sm hidden-md hidden-lg">
                                        <div class="btn-group">
                                            <a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#"><i
                                                class="fa fa-cog"></i><span class="caret"></span></a>
                                            <ul role="menu" class="dropdown-menu pull-right">
                                                @if (doctor.SecurityModel.Edit)
                                                {
                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/Doctor/EditDoctor?id=@doctor.DoctorID">
                                                        <i class="fa fa-edit"></i>Edit </a></li>
                                                }
                                                @if (doctor.SecurityModel.Delete)
                                                {
                                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#panel-remove"><i
                                                        class="fa fa-times"></i>Remove </a></li>
                                                }
                                            </ul>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                                                i++;
                                }
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end: DYNAMIC TABLE PANEL -->
    </div>
</div>
<!-- end: PAGE CONTENT-->
@section Scripts{
    <script type="text/javascript" src="~/Content/assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/DataTables/media/js/DT_bootstrap.js"></script>
    <script type="text/javascript" src="~/Content/assets/js/table-data.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            TableData.init();

            if ($('#viewCreatedBy').val() == 'True') {
                $('td:nth-child(6),th:nth-child(6)').show();
            }
            else if ($('#viewCreatedBy').val() == 'False') {
                $('td:nth-child(6),th:nth-child(6)').hide();
            }
            else { }

            if ($('#viewCreatedOn').val() == 'True') {
                $('td:nth-child(7),th:nth-child(7)').show();
            }
            else if ($('#viewCreatedOn').val() == 'False') {
                $('td:nth-child(7),th:nth-child(7)').hide();
            }
            else { }

            if ($('#viewModifiedBy').val() == 'True') {
                $('td:nth-child(8),th:nth-child(8)').show();
            }
            else if ($('#viewModifiedBy').val() == 'False') {
                $('td:nth-child(8),th:nth-child(8)').hide();
            }
            else { }

            if ($('#viewModifiedOn').val() == 'True') {
                $('td:nth-child(9),th:nth-child(9)').show();
            }
            else if ($('#viewModifiedOn').val() == 'False') {
                $('td:nth-child(9),th:nth-child(9)').hide();
            }
            else { }
        });

        function updateView() {
            if ($('#viewCreatedBy').is(":checked")) {
                $('td:nth-child(6),th:nth-child(6)').show();
            }
            else {
                $('td:nth-child(6),th:nth-child(6)').hide();
            }

            if ($('#viewCreatedOn').is(":checked")) {
                $('td:nth-child(7),th:nth-child(7)').show();
            }
            else {
                $('td:nth-child(7),th:nth-child(7)').hide();
            }

            if ($('#viewModifiedBy').is(":checked")) {
                $('td:nth-child(8),th:nth-child(8)').show();
            }
            else {
                $('td:nth-child(8),th:nth-child(8)').hide();
            }

            if ($('#viewModifiedOn').is(":checked")) {
                $('td:nth-child(9),th:nth-child(9)').show();
            }
            else {
                $('td:nth-child(9),th:nth-child(9)').hide();
            }
        }


        //Modal OK
        var id = '';
        $('tr').click(function () {
            id = $(this).attr('id');
            var name = $(this).attr('name');
            document.getElementById('modalbody').innerHTML = 'Are you sure you want to remove ' + name + '?';
        });

        function execRemove() {
            window.location.href = "/Doctor/DeleteDoctor?id=" + id;
            return false;
        }
    </script>
}